jobs:
  include:
    - stage: database migration
      language: java
      jdk: openjdk11
      addons:
        mariadb: '10.2'
      install: skip
      before_script:
        - echo 'starting migration'
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
        - cf install-plugin -r "CF-Community" mysql-plugin -f
        - cf login -a https://api.run.pivotal.io -u [CF username] -s [CF Space Name] -o [CF Org Name] -p [CF Password]
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.1.1/flyway-commandline-5.1.1-linux-x64.tar.gz | tar xvz
        - flyway-*/flyway -url="[Get From VCAP]" -locations=filesystem:db -user=[Get From VCAP] -password=[Get From VCAP] clean migrate